### ISSUE TITLE
Object boroughs is missing in 15.3.5

### ISSUE THREAD

**Issue by heike** [srvanderplas/stat-computing-r-python#29]
borough_zip <- [read_csv](https://readr.tidyverse.org/reference/read_delim.html)("https://raw.githubusercontent.com/srvanderplas/unl-stat850/main/data/nyc_zip_borough.csv")

**Comment by srvanderplas** [comment]
Fixed in bc5ed17c735edb72f1604309cc3ed2880efd9059
