### ISSUE TITLE
Include a mini discussion of boolean operators

### ISSUE THREAD

**Issue by heike** [srvanderplas/stat-computing-r-python#34]
Between chapters 9 and 10 a section on Boolean operators would make sense, because booleans are used in the basic filter functions of the data structures in chapter 10

**Comment by srvanderplas** [comment]
Might it make sense to add a section to Ch 8, where boolean/logical variables are introduced, basically saying that a boolean variable is created through the use of a boolean operator?

**Comment by heike** [comment]
Those are comparison operators - not Boolean operators

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by srvanderplas** [comment]
Ok, so yes, you can create a boolean through a comparison operator as well, e.g. 3 > 5 is False, but it seems like it might make sense to talk about 0 = False, 1 = True, as well as logical vs. bitwise operators at that point. And once you've done that, it makes sense to talk about combining logical values.

**Comment by srvanderplas** [comment]
Fixed at least boolean/demorgan by adding a section in the chapter on using functions.
